name: Build Docker Image
on:
  push:
    branches:
      - main
env:
  MAVEN_IMAGE_TAG: maven_actions:updated
  NEXUS_IMAGE_TAG: nexus_actions:updated
  SONAR_IMAGE_TAG: sonar_actions:updated
  JENKIN_IMAGE_TAG: jenkins_actions:updated
jobs:
  MavenNexus:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Maven image to Docker Hub
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: docker.io/kavyakolla/${{ env.MAVEN_IMAGE_TAG }}
          
      - name: Push Nexus image to Docker Hub
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Nexus
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.NEXUS_IMAGE_TAG }}

  sonar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Sonar Image to Docker Hub
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Sonarqube
          push: true
          tags: docker.io/kavyakolla/${{ env.SONAR_IMAGE_TAG }}
  Jenkin:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push Jenkin Image to Docker Hub
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Jenkin
        push: true
        tags: docker.io/kavyakolla/${{ env.JENKIN_IMAGE_TAG }}
