name: Build Docker Image
on:
  push:
    branches:
      - main
env:
  MAVEN_IMAGE_TAG: maven_actions:updated
  NEXUS_IMAGE_TAG: nexus_actions:updated
  SONAR_IMAGE_TAG: sonar_actions:updated
jobs:
  mavennexus:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: docker.io/kavyakolla/${{ env.MAVEN_IMAGE_TAG }}
          
      - name: Push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Nexus
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.NEXUS_IMAGE_TAG }}

  sonar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Create Environment File
        run: echo "SONAR_IMAGE_TAG=sonar_actions:updated" >> $GITHUB_ENV

      - name: Push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Sonarqube
          push: true
          tags: docker.io/kavyakolla/${{ env.SONAR_IMAGE_TAG }}
