name: Build Docker Image
on:
  push:
    branches:
      - main
env:
  IMAGE_TAG: maven_actions:v2
  Nexus_image: nexus_actions:v1
jobs:
  mavennexus:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Environment File
        run: |
          echo "MAVEN_IMAGE_TAG=maven_actions:updated" >> $GITHUB_ENV
          echo "NEXUS_IMAGE_TAG=nexus_actions:updated" >> $GITHUB_OUTPUT
          echo "SONAR_IMAGE_TAG=sonar_actions:updated" >> $GITHUB_OUTPUT


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/kavyakolla/$MAVEN_IMAGE_TAG
          
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Nexus
          push: true
          tags: docker.io/${{secrets.DOCKER_USERNAME }}/${{NEXUS_IMAGE_TAG}}
      - name: Run nexus Container
        run: |
         docker run -d -p 8087:8081 --name nexus ${{ secrets.DOCKER_USERNAME }}/${{env.Nexus_image}}
  sonar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2



      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Sonarqube
          push: true
          tags: docker.io/kavyakolla/${{SONAR_IMAGE_TAG}}
        
    
